cart/urls.py
from typing import List

from django.urls import (path, URLPattern,re_path)
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns: List[URLPattern] = [
    path(route='', view=views.CartView.as_view(), name='summary'),
    path(route='payment/', view=views.PaymentView.as_view(), name='payment'),
    path(route='checkout/', view=views.CheckoutView.as_view(), name='checkout'),
    path(route='thank-you/', view=views.ThankYouView.as_view(), name='thank-you'),
    path(route='shop/', view=views.ProductListView.as_view(), name='product-list'),
    # path(route='sea/', view=views.ProductSearchListView.as_view(), name='search'),
    path(route='orders/<pk>/', view=views.OrderDetailView.as_view(), name='order-detail'),
    path(route='webhooks/stripe/', view=views.stripe_webhook_view, name='stripe-webhook'),
    path(route='shop/<slug>/', view=views.ProductDetailView.as_view(), name='product-detail'),
    path(route='confirm-order/', view=views.ConfirmOrderView.as_view(), name='confirm-order'),
    path(route='payment/stripe/', view=views.StripePaymentView.as_view(), name='payment-stripe'),
    path(route="rating/",view=views.rating,name="rating"),
    path(
        route='increase-quantity/<pk>/',
        view=views.IncreaseQuantityView.as_view(),
        name='increase-quantity',
    ),
    path(
        route='decrease-quantity/<pk>/',
        view=views.DecreaseQuantityView.as_view(),
        name='decrease-quantity',
    ),
    path(
        route='remove-from-cart/<pk>/',
        view=views.RemoveFromCartView.as_view(),
        name='remove-from-cart',
    ),
]

app_name: str = 'cart'
# urlpatterns += staticfiles_urlpatterns()

__all__ = ('app_name', 'urlpatterns',)

ecom/urls.py
from typing import List

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import (path, include, URLPattern)
from djapi.views import product_list
from search import urls as urls_search

from core import views
from search import views as  searchviews

urlpatterns: List[URLPattern] = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('staff/', include('staff.urls', namespace='staff')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('search/', searchviews.ProductSearchListView.as_view(), name='search'),
    path('products-create/', product_list ,name='products-api'),
]

if settings.DEBUG:
    urlpatterns += static(prefix=settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

__all__ = ('urlpatterns',)

cart/models.py
from decimal import Decimal
from typing import Tuple

from django.contrib.auth import get_user_model
from django.db import models
from django.shortcuts import reverse
from django.utils.text import slugify

User = get_user_model()

class MainCategory(models.Model):
    name=models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.name


class Category(models.Model):
    main_category=models.ForeignKey(MainCategory,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name: str = 'Category'
        verbose_name_plural: str = "Categories"

    def __str__(self) -> str:
        return self.name


class Address(models.Model):
    SHIPPING_ADDRESS_TYPE: str = 'S'
    BILLING_ADDRESS_TYPE: str = 'B'
    ADDRESS_CHOICES: Tuple[Tuple[str, str], ...] = (
        (BILLING_ADDRESS_TYPE, 'Billing'),
        (SHIPPING_ADDRESS_TYPE, 'Shipping'),
    )

    city = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=20)
    default = models.BooleanField(default=False)
    address_line_1 = models.CharField(max_length=150)
    address_line_2 = models.CharField(max_length=150)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)

    class Meta:
        verbose_name: str = 'Address'
        verbose_name_plural: str = 'Addresses'

    def __str__(self) -> str:
        return ', '.join([
            self.address_line_1,
            self.address_line_2,
            self.city,
            self.zip_code,
        ])


class ColourVariation(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name


class SizeVariation(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name


class Product(models.Model):
    description = models.TextField(null=True, blank=True)
    slug = models.SlugField(unique=True)
    stock = models.IntegerField(default=0)
    title = models.CharField(max_length=150)
    active = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    rating=models.FloatField(default=2.5)
    image = models.CharField(max_length=500, null=True, blank=True)
    price = models.DecimalField(default=0, max_digits=9, decimal_places=2, )
    primary_category = models.ForeignKey(
        to=MainCategory,
        on_delete=models.CASCADE,
        related_name='primary_products',
        blank=True, null=True,
    )
    available_sizes = models.ManyToManyField(SizeVariation, null=True, blank=True)
    available_colours = models.ManyToManyField(ColourVariation, null=True, blank=True)
    # secondary_categories = models.ManyToManyField(to=Category, null=True, blank=True)

    def __str__(self) -> str:
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(value=self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self) -> str:
        return reverse("cart:product-detail", kwargs={'slug': self.slug})

    def get_update_url(self) -> str:
        return reverse("staff:product-update", kwargs={'pk': self.pk})

    def get_delete_url(self) -> str:
        return reverse("staff:product-delete", kwargs={'pk': self.pk})

    def get_price(self) -> str:
        return "{:.2f}".format(self.price / 100)

    @property
    def in_stock(self) -> bool:
        return self.stock > 0


class OrderItem(models.Model):
    quantity = models.PositiveIntegerField(default=1)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    size = models.ForeignKey(to=SizeVariation, null=True, blank=True, on_delete=models.CASCADE)
    colour = models.ForeignKey(to=ColourVariation, null=True, blank=True, on_delete=models.CASCADE)
    order = models.ForeignKey(
        to="Order",
        related_name='items',
        on_delete=models.CASCADE,
    )

    def __str__(self) -> str:
        return f"{self.quantity} x {self.product.title}"

    def get_raw_total_item_price(self) -> Decimal:
        return self.quantity * self.product.price

    def get_total_item_price(self) -> str:
        price = self.get_raw_total_item_price()  # 1000
        return "{:.2f}".format(price / 100)


class Order(models.Model):
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(blank=True, null=True)
    ordered = models.BooleanField(default=False)
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        blank=True, null=True,
    )
    billing_address = models.ForeignKey(
        to=Address,
        on_delete=models.SET_NULL,
        related_name='billing_address',
        blank=True, null=True,
    )
    shipping_address = models.ForeignKey(
        to=Address,
        on_delete=models.SET_NULL,
        related_name='shipping_address',
        blank=True, null=True,
    )

    def __str__(self) -> str:
        return self.reference_number

    @property
    def reference_number(self) -> str:
        print("order no",self.pk)
        return f"ORDER-{self.pk}"

    def get_raw_subtotal(self) -> float:
        total = 0
        for order_item in self.items.all():
            total += order_item.get_raw_total_item_price()
        return total

    def get_subtotal(self) -> str:
        subtotal = self.get_raw_subtotal()
        return "{:.2f}".format(subtotal / 100)

    def get_raw_total(self) -> float:
        subtotal = self.get_raw_subtotal()
        # add tax, add delivery, subtract discounts
        # total = subtotal - discounts + tax + delivery
        return subtotal

    def get_total(self) -> str:
        total = self.get_raw_total()
        return "{:.2f}".format(total / 100)


class Payment(models.Model):
    PAYPAL_PAYMENT_METHOD: str = 'PayPal'

    PAYMENT_METHODS: Tuple[Tuple[str, str], ...] = (
        (PAYPAL_PAYMENT_METHOD, 'PayPal'),
    )

    amount = models.FloatField()
    raw_response = models.TextField()
    successful = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHODS, )
    order = models.ForeignKey(
        to=Order,
        on_delete=models.CASCADE,
        related_name='payments',
    )

    def __str__(self) -> str:
        return self.reference_number

    @property
    def reference_number(self):
        return f"PAYMENT-{self.order}-{self.pk}"


class StripePayment(models.Model):
    amount = models.FloatField(default=0)
    successful = models.BooleanField(default=False)
    payment_intent_id = models.CharField(max_length=100)
    timestamp = models.DateTimeField(auto_now_add=True)
    order = models.ForeignKey(
        to=Order,
        on_delete=models.CASCADE,
        related_name='stripe_payments',
    )

    def __str__(self) -> str:
        return self.reference_number

    @property
    def reference_number(self) -> str:
        return f"STRIPE-PAYMENT-{self.order}-{self.pk}"


__all__ = (
    'Category',
    'Address',
    'ColourVariation',
    'SizeVariation',
    'Product',
    'OrderItem',
    'Order',
    'Payment',
    'StripePayment',
)

cart/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import (
    OrderItem,
    Product,
    Address
)

User = get_user_model()


class AddToCartForm(forms.ModelForm):
    quantity = forms.IntegerField(min_value=1)
    # size = forms.ModelChoiceField(queryset=SizeVariation.objects.none())
    # colour = forms.ModelChoiceField(queryset=ColourVariation.objects.none())

    class Meta:
        model = OrderItem
        fields = ('quantity', )

    def __init__(self, *args, **kwargs):
        self.product_id = kwargs.pop('product_id')
        product = Product.objects.get(id=self.product_id)
        super().__init__(*args, **kwargs)

        # self.fields['colour'].queryset = product.available_colours.all()
        # self.fields['size'].queryset = product.available_sizes.all()

    def clean(self):
        product = Product.objects.get(id=self.product_id)
        quantity = self.cleaned_data['quantity']
        if product.stock < quantity:
            raise forms.ValidationError(
                f"The maximum stock available is {product.stock}"
            )


class AddressForm(forms.Form):
    selected_shipping_address = forms.ModelChoiceField(
        queryset=Address.objects.none(),
        required=False,
    )
    selected_billing_address = forms.ModelChoiceField(
        queryset=Address.objects.none(),
        required=False,
    )
    billing_city = forms.CharField(required=False)
    
    billing_zip_code = forms.CharField(required=False)
    
    billing_address_line_1 = forms.CharField(required=False)
    billing_address_line_2 = forms.CharField(required=False)
    shipping_city = forms.CharField(required=False)
    shipping_zip_code = forms.CharField(required=False)
    
    shipping_address_line_1 = forms.CharField(required=False)
    shipping_address_line_2 = forms.CharField(required=False)

    

    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id')
        super().__init__(*args, **kwargs)

        user = User.objects.get(pk=user_id)

        shipping_address_qs = Address.objects.filter(
            user=user,
            address_type=Address.SHIPPING_ADDRESS_TYPE,
        )
        billing_address_qs = Address.objects.filter(
            user=user,
            address_type=Address.BILLING_ADDRESS_TYPE,
        )

        self.fields['selected_shipping_address'].queryset = shipping_address_qs
        self.fields['selected_billing_address'].queryset = billing_address_qs

    def clean(self):
        data = self.cleaned_data

        selected_shipping_address = data.get('selected_shipping_address', None)
        if selected_shipping_address is None:
            if not data.get('shipping_address_line_1', None):
                self.add_error(
                    "shipping_address_line_1",
                    "Please fill in this field"
                )
            if not data.get('shipping_address_line_2', None):
                self.add_error(
                    "shipping_address_line_2",
                    "Please fill in this field",
                )
            if not data.get('shipping_zip_code', None):
                self.add_error(
                    "shipping_zip_code",
                    "Please fill in this field",
                )
            if not data.get('shipping_city', None):
                self.add_error("shipping_city", "Please fill in this field")

        selected_billing_address = data.get('selected_billing_address', None)
        if selected_billing_address is None:
            if not data.get('billing_address_line_1', None):
                self.add_error(
                    "billing_address_line_1",
                    "Please fill in this field"
                )
            if not data.get('billing_address_line_2', None):
                self.add_error(
                    "billing_address_line_2",
                    "Please fill in this field"
                )
            if not data.get('billing_zip_code', None):
                self.add_error(
                    "billing_zip_code",
                    "Please fill in this field"
                )
            if not data.get('billing_city', None):
                self.add_error("billing_city", "Please fill in this field")


class StripePaymentForm(forms.Form):
    selectedCard = forms.CharField()

class ProfileSearchForm(forms.Form):
    name = forms.CharField(required=False)


__all__ = (
    'AddToCartForm',
    'AddressForm',
    'StripePaymentForm',
)

ecom/settings/templates/cart/cart.html
{% extends "base.html" %}

{% block content %}

{% load static%}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">Cart</strong>
            </div>
        </div>
    </div>
</div>


<div class="site-section"style="background-image: url('{% static 'images/cart.png' %}')">
    <div class="container"  style="background-color:rgba(250,225,221,255)">
        <div class="row mb-5">
            <div class="col-md-12">
                <div class="site-blocks-table">
                    <table>
                        <thead>
                            <tr>
                                <th>Image</th>
                                <th>Product</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in order.items.all %}
                            <tr>
                                <td class="product-thumbnail">
                                    <img src="{{ item.product.image.url }}" class="img-fluid">
                                </td>
                                <td class="product-name">
                                    <h2 class="h5 text-black">{{ item.product.title }}</h2>
                                    <small>Size: {{ item.size.name }}</small>
                                    <small>Colour: {{ item.colour.name }}</small>
                                </td>
                                <td>${{ item.product.get_price }}</td>
                                <td>
                                    <div class="input-group mb-3" style="max-width: 120px;">
                                        <div class="input-group-prepend">
                                            <a href="{% url 'cart:decrease-quantity' item.id %}"
                                                class="btn btn-outline-primary">
                                                &minus;
                                            </a>
                                        </div>
                                        <input type="text" class="form-control text-center" value="{{ item.quantity }}">
                                        <div class="input-group-append">
                                            <a href="{% url 'cart:increase-quantity' item.id %} "
                                                class="btn btn-outline-primary">
                                                &plus;
                                            </a>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    ${{ item.get_total_item_price }}
                                </td>
                                <td>
                                    <a href="{% url 'cart:remove-from-cart' item.id %}"
                                        class="btn btn-primary btn-sm">X</a>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colSpan='6'>
                                    There are no items in your cart.
                                    <a href="{% url 'cart:product-list' %}">Continue shopping</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        {% if order.items.count > 0 %}
        <div class="row">
            <div class="col-md-6">
                <div class="row mb-5">
                    <div class="col-md-12">
                        <a class="btn btn-outline-primary btn-sm btn-block"
                            href="{% url 'cart:product-list' %}">Continue shopping</a>
                    </div>
                </div>
            </div>

            <div class="col-md-6 pl-5">
                <div class="row justify-content-end">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-12 text-right border-bottom mb-5">
                                <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-6">
                                <span class="text-black">Subtotal</span>
                            </div>
                            <div class="col-md-6 text-right">
                                <strong class="text-black">${{ order.get_subtotal }}</strong>
                            </div>
                        </div>

                        <div class="row mb-5">
                            <div class="col-md-6">
                                <span class="text-black">Total</span>
                            </div>
                            <div class="col-md-6 text-right">
                                <strong class="text-black">${{ order.get_total }}</strong>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <a class="btn btn-primary btn-lg py-3 btn-block" href="{% url 'cart:checkout' %}">Proceed to checkout</a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div>
        {% endif %}

    </div>
</div>

{% endblock content %}

ecom/settings/templates/cart/payment.html
{% extends "base.html" %}

{% block content %}

<style>
    lds-ring {
        display: inline-block;
        position: relative;
        width: 80px;
        height: 80px;
    }

    .lds-ring div {
        box-sizing: border-box;
        display: block;
        position: absolute;
        width: 64px;
        height: 64px;
        margin: 8px;
        border: 8px solid rgb(155, 81, 81);
        border-radius: 50%;
        animation: lds-ring 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite;
        border-color: rgb(155, 81, 81) transparent transparent transparent;
    }

    .lds-ring div:nth-child(1) {
        animation-delay: -0.45s;
    }

    .lds-ring div:nth-child(2) {
        animation-delay: -0.3s;
    }

    .lds-ring div:nth-child(3) {
        animation-delay: -0.15s;
    }

    @keyframes lds-ring {
        0% {
            transform: rotate(0deg);
        }

        100% {
            transform: rotate(360deg);
        }
    }
</style>

<div class='container'>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="alert alert-success" role="alert" id="alertSuccess" style="display: none;">
                Your payment was successful.
            </div>
            <div class="alert alert-danger" role="alert" id="alertFailure" style="display: none;">
                Your payment failed. Please try again.
            </div>

            <div class="text-center py-3">
                <div id="loader" class="lds-ring" style="margin: auto; display: none;">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>

            <div id='paymentInfo'>
                <p>Order total: ${{ order.get_total }}</p>
                <h4>Select a payment method</h4>
                <div>
                    <a href="{% url 'cart:payment-stripe' %}" class="btn btn-secondary btn-block mb-3">Stripe</a>
                </div>
                <div id="paypal-button-container"></div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}


{% block scripts %}

<script src="https://www.paypal.com/sdk/js?client-id=AeFbXQxVuKX0SiWi6DdBQmUMxbeadLWufJASt-1v54RgrzgNnDkhcCd6AEb_RyxNjn-LVoSyS7Xr9Wzj">
</script>

<script>
    console.log("inside script");

    const loader = document.getElementById('loader');
    const paymentInfo = document.getElementById('paymentInfo');

    function toggleLoader(on) {
        loader.style.display = on === true ? "block" : "none";
        paymentInfo.style.display = on === true ? "none" : "block";
        console.log("inside toggle script");
    }

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                console.log("inside get ccokie script");
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

    function sendOrderConfirmed(details) {
        console.log("inside order script");
        return fetch("{% url 'cart:confirm-order' %}", {
            method: "post",
            body: JSON.stringify(details),
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": csrftoken
            }
        })
    }

    paypal.Buttons({
        createOrder: function (data, actions) {
            console.log("inside create order script");

            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: '{{ order.get_total }}'
                    }
                }]
            });
        },
        onApprove: function (data, actions) {
            toggleLoader(true);
            // This function captures the funds from the transaction.
            return actions.order.capture().then(function (details) {
                // This function shows a transaction success message to your buyer.
                sendOrderConfirmed(details).then(res => {
                    toggleLoader(false);
                    const alertSuccess = document.getElementById('alertSuccess');
                    alertSuccess.style.display = 'block';
                    setTimeout(function () {
                        window.location.replace("{{ CALLBACK_URL }}")
                    }, 3000);
                })
            })
                .catch(err => {
                    const alertFailure = document.getElementById('alertFailure');
                    alertFailure.style.display = 'block';
                })
                .finally(() => toggleLoader(false));
        }
    }).render('#paypal-button-container');
</script>

{% endblock scripts %}

ecom/settings/templates/cart/product_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">{{ product.title }}</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-6">
                <img src="{{ product.image }}" class="img-fluid">
            </div>
            <div class="col-md-6" style="background-color: rgb(226, 221, 215);">
                <h2 class="text-black">{{ product.title }}</h2>
                <p>{{ product.description }}</p>
                <p>Product Rating: {{ product.rating }} Stars</p>
                {% if product.in_stock %}
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type='submit' class="btn btn-sm btn-primary buy-now">Add to cart</button>
                </form>
                {% else %}
                <p>This item is out of stock</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

ecom/settings/templates/cart/product_list.html
{% extends "base.html" %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-black">Shop</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row">
     
        <div class="col-2">
            
                <h3 class="h6 text-uppercase text-black">Categories</h3>
                <ul>
                    {% for maincategory in mainCategory %}
                    <li class="mb-1">
                        <!-- ?mainCategory={{ maincategory.name }} -->
                        <a href="{% url 'cart:product-list' %}?mainCategory={{maincategory.name}}" class="d-flex">
                            <span>{{ maincategory.name }}</span>  <i class="far fa-angle-down"></i>
                        </a>
                        <ul class="mega-menu">
                            {% for category in maincategory.category_set.all %}
                            <li class="mb-2">
                                <!-- ?category={{ category.name }} -->
                                <a href="{% url 'cart:product-list'%}?category={{category.name}}" class="d-flex">
                                    <span>{{ category.name }}</span>
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                    </li>

                    
                    {% endfor %}
                </ul>
           
        </div>
        <div class="col">
        <div class="row mb-5">
            <div class="col-md-8 mb-2">
                <div class="row mb-5" >
                    {% for product in object_list %}
                        <div class="col-sm-6 col-md-6 col-lg-4 mb-4" data-aos='fade-up' style="background: rgba(232,230,227,255);" >
                            <figure class="block-4-image">
                                <a href="{{ product.get_absolute_url }}"><img src="{{ product.image }}" class="img-fluid"></a>
                            </figure>

                            <div class="block-4-text p-4">
                                <a href="{{ product.get_absolute_url }}">
                                    <h3>{{ product.title }}</h3>
                                </a>
                                <p class="mb-0">{{ product.description }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
      
        </div>
    </div>
    </div>
    </div>
</div>

{% endblock content %}

ecom/settings/templates/cart/thanks.html
{% extends "base.html" %}
{% load static%}

{% block content %}

{% block additional_styles %}
<style>
   body {
    background-image: url('{% static 'images/thankyou.png' %}');
   }
</style>
{% endblock %}

<div  >
    <h1>Thanks for ordering </h1>
</div>

{% endblock content %}